Concept kong secrets on spoke clusters

diff --git a/tests/all-clustering-naked.expected.yaml b/tests/all-clustering-naked.expected.yaml
--- a/tests/all-clustering-naked.expected.yaml
+++ b/tests/all-clustering-naked.expected.yaml
@@ -27,6 +27,50 @@ data:
       --resource-name kong-cp-kong \
       --patch "{\"spec\": { \"template\" : { \"spec\" : {\"containers\":[{\"name\":\"proxy\",\"env\": [{ \"name\" : \"KONG_ADMIN_API_URI\", \"value\": \"$(oc get route -n kong  kong-cp-kong-admin -ojsonpath='{.spec.host}')\" }]}]}}}}"  --patch-type 'application/strategic-merge-patch+json'
 ---
+# Source: kong-clustering/templates/post-deploy-dp-license.yaml
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  namespace: test
+  name: kong-clustering-post-deploy-dp-license
+data:
+  post-deploy.sh: |
+    #!/bin/bash
+    set -eu
+    argocd login --username admin \
+      $(oc get routes -n unmanaged- -gitops-server -otemplate='{{ .spec.host }}') \
+      --password $(oc get secret -n unmanaged- -gitops-cluster -ojsonpath='{.data.admin\.password}' | base64 -d) \
+      --insecure \
+      --grpc-web
+    if ! oc get secret -n kong kong-clustering-enterprise-license; then
+      echo "secret not found"
+      exit 1
+    fi
+
+    if ! oc get appprojects -n unmanaged- dataplane; then
+      echo "dataplane project cannot be retrieved"
+      exit 1
+    fi
+
+    if ! oc get appprojects -n unmanaged- controlplane; then
+      echo "controlplane project cannot be retrieved"
+      exit 1
+    fi
+
+    if ! oc get secret kong-clustering-enterprise-license -n kong -o jsonpath='{.data.license}'; then
+      echo "kong-enterprise license not found"
+      exit 1
+    fi
+
+    # for patching enterprise license in data plane
+    SECRET=$(oc get secret kong-clustering-enterprise-license -n kong -o jsonpath='{.data.license}')
+
+    argocd app patch-resource kong-dp \
+    --kind Secret --resource-name kong-clustering-enterprise-license \
+    --namespace=kong \
+    --patch "{\"data\": {\"license\":\"$SECRET\"} }" \
+    --patch-type 'application/strategic-merge-patch+json'
+---
 # Source: kong-clustering/templates/post-deploy-dp.yaml
 apiVersion: v1
 kind: ConfigMap
@@ -156,6 +200,35 @@ spec:
         resources: {}
         volumeMounts:
         - name: post-deploy
+          mountPath: /opt/scripts
+        securityContext:
+           runAsUser: 0
+        command: ["sh","-c","/opt/scripts/post-deploy.sh"]
+---
+# Source: kong-clustering/templates/post-deploy-dp-license.yaml
+apiVersion: batch/v1
+kind: Job
+metadata:
+  namespace: test
+  name: kong-clustering-post-deploy-dp-license
+  generateName: deploy-dp-license
+spec:
+  backoffLimit: 40
+  template:
+    spec:
+      restartPolicy: OnFailure
+      serviceAccountName: kong-clustering-gitops
+      volumes:
+      - name: post-deploy-dp-license
+        configMap:
+          name: kong-clustering-post-deploy-dp-license
+          defaultMode: 0711 
+      containers:
+      - image: quay.io/ecosystem-appeng/argocd-helper:1.0
+        name: post-deploy-dp-license
+        resources: {}
+        volumeMounts:
+        - name: post-deploy-dp-license
           mountPath: /opt/scripts
         securityContext:
            runAsUser: 0
